name: clippy
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clippy:
    name: Runs "cargo clippy" on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Clippy
        run: cargo clippy --all
