name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Runs "cargo test" on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Tests
        run: cargo test -- --test-threads=1
